name: Push library on npm
on:
  push:
    branches:
      - master
jobs:
    push-on-npm:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Install dependecies
              run: |
                  yarn
            - name: Build project
              run: |
                  yarn build
            - name: Deploy
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release
            - run: echo "Build succesful"
