name: Push library on npm
on:
    pull_request:
        types: [closed]
        branches: [master]
jobs:
    push-on-npm:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Install dependecies
              run: |
                  yarn
            - name: Build project
              run: |
                  yarn build
            - run: echo "Build succesful"
